#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Run it like usual executable script:
#
# > ./run-smb.yml
#
---
- name: Setup smb server
  hosts: samba_servers
  gather_facts: false

  roles:
    - ageres210784.smb
