stages:
  - preview
  - apply
  - triggering

preview:
  stage: preview
  image: lyricistmarbling/ansible-ci-image:latest
  environment:
    name: preview
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
  script: 
    - python3 tools/ci-script.py --preview --target_branch origin/master

apply:
  stage: apply
  image: lyricistmarbling/ansible-ci-image:latest
  environment:
    name: master
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE != "schedule"'
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
  before_script:
    - |
      mkdir ~/.ssh
      eval "$(ssh-agent -s)"
      echo $TARGET_HOST_SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-add ~/.ssh/id_rsa
  script: 
    - python3 tools/ci-script.py --apply --target_branch $CI_COMMIT_BEFORE_SHA

trigger-job:
  stage: triggering
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE != "schedule"'
      changes:
        - 'tools/requirements.txt'
  trigger:
    project: 'oomag/infrastructure/ansible-ci-image'
    branch: master
    strategy: depend
