---
- src: andrewgodgivens.prometheus_smartctl_exporter
- src: andrewgodgivens.ansible_prometheus_ipmi_exporter
- src: mikecher.ansible_prometheus_ssl_exporter
- src: sorrowless.prometheus_blackbox_exporter
- src: sorrowless.prometheus_domain_exporter
- src: sorrowless.prometheus_grok_exporter
- src: sorrowless.prometheus_mysqld_exporter
- src: sorrowless.prometheus_node_exporter
- src: sorrowless.prometheus_postgres_exporter
- src: sorrowless.prometheus_scripts_exporter
- src: sorrowless.prometheus_statsd_exporter
- src: sorrowless.cadvisor
- src: sorrowless.docker
- src: sorrowless.victoriametrics
- src: sorrowless.prometheus_server
- src: sorrowless.prometheus_alertmanager
- src: sorrowless.grafana
- src: sorrowless.tls
- src: sorrowless.nginx
- src: sorrowless.haproxy
